name: Create Service

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: Service Name
        required: true
        type: string

      description:
        description: Service Description
        required: true
        type: string

      team_name:
        description: Team Name
        required: true
        type: string

jobs:
  create_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Create repository from template
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.createUsingTemplate({
              template_owner: 'seanvucas0-ai',
              template_repo: 'dotnet-webapi-template',
              owner: 'seanvucas0-ai',
              name: '${{ github.event.inputs.service_name }}'
            });
