name: Create Service

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: Service Name
        required: true
        type: string

      description:
        description: Service Description
        required: true
        type: string

      team_name:
        description: Team Name
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update README
        run: |
          cat << EOF > README.md
          # ${{ github.event.inputs.service_name }}

          ## Description

          ${{ github.event.inputs.description }}

          ## Team

          Owned by ${{ github.event.inputs.team_name }}
          EOF

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add README.md
          git commit -m "Update service details" || exit 0
          git push
